apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::057380754576:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DAQQU3RI9XX9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::057380754576:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T00:28:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1599"
  uid: 0b6b99ed-e282-43d7-abac-6086f6553ffa
